import { Archivo_Narrow } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";

const archivo_Narrow = Archivo_Narrow({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`bg-black text-white ${archivo_Narrow.className}`}>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
